name: 'Easy generalized deployments'
description: 'Kick off an easy generalized deployment'
inputs:
  env-vars-for-codebuild:
    description: 'Comma separated list of environment variables to send to CodeBuild'
    required: false
outputs:
  aws-build-id:
    description: 'The AWS CodeBuild Build ID for this build.'
runs:
  using: 'node12'
  main: 'dist/index.js'
